<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Services\Llm\ProviderOptionsResolver;
use Illuminate\Console\Command;

class GenerateProviderOptionsCommand extends Command
{
    /**
     * The name and signature of the console command.
     */
    protected $signature = 'threadql:generate-provider-options
                            {--path= : Custom output path for the generated file}';

    /**
     * The console command description.
     */
    protected $description = 'Generate providerOptions.js from the ProviderOptionsResolver for the admin frontend';

    /**
     * Execute the console command.
     */
    public function handle(ProviderOptionsResolver $resolver): int
    {
        $options = $resolver->getAllAdapterOptions();
        $adapters = $resolver->getSupportedAdapters();
        $defaultUrls = $resolver->getDefaultUrls();

        $outputPath = $this->option('path')
            ?? resource_path('js/admin/generated/providerOptions.js');

        $dir = dirname($outputPath);
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $json = json_encode($options, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $adaptersJson = json_encode($adapters, JSON_PRETTY_PRINT);
        $defaultUrlsJson = json_encode($defaultUrls, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

        $content = <<<JS
        /**
         * Auto-generated by: php artisan threadql:generate-provider-options
         * Do not edit manually.
         */

        export const providerOptions = {$json};

        export const adapterOptions = {$adaptersJson};

        export const defaultUrls = {$defaultUrlsJson};
        JS;

        file_put_contents($outputPath, $content);

        $this->info("Provider options written to: {$outputPath}");

        return self::SUCCESS;
    }
}
