const timezones = [
    { value: 'Pacific/Midway', label: 'UTC-11:00 Pacific/Midway', offset: -11 },
    { value: 'Pacific/Honolulu', label: 'UTC-10:00 Pacific/Honolulu', offset: -10 },
    { value: 'America/Anchorage', label: 'UTC-09:00 America/Anchorage', offset: -9 },
    { value: 'America/Los_Angeles', label: 'UTC-08:00 America/Los_Angeles', offset: -8 },
    { value: 'America/Denver', label: 'UTC-07:00 America/Denver', offset: -7 },
    { value: 'America/Chicago', label: 'UTC-06:00 America/Chicago', offset: -6 },
    { value: 'America/New_York', label: 'UTC-05:00 America/New_York', offset: -5 },
    { value: 'America/Caracas', label: 'UTC-04:00 America/Caracas', offset: -4 },
    { value: 'America/Sao_Paulo', label: 'UTC-03:00 America/Sao_Paulo', offset: -3 },
    { value: 'Atlantic/Azores', label: 'UTC-01:00 Atlantic/Azores', offset: -1 },
    { value: 'UTC', label: 'UTC', offset: 0 },
    { value: 'Europe/London', label: 'UTC+00:00 Europe/London', offset: 0 },
    { value: 'Europe/Amsterdam', label: 'UTC+01:00 Europe/Amsterdam', offset: 1 },
    { value: 'Europe/Berlin', label: 'UTC+01:00 Europe/Berlin', offset: 1 },
    { value: 'Africa/Cairo', label: 'UTC+02:00 Africa/Cairo', offset: 2 },
    { value: 'Europe/Moscow', label: 'UTC+03:00 Europe/Moscow', offset: 3 },
    { value: 'Asia/Dubai', label: 'UTC+04:00 Asia/Dubai', offset: 4 },
    { value: 'Asia/Karachi', label: 'UTC+05:00 Asia/Karachi', offset: 5 },
    { value: 'Asia/Kolkata', label: 'UTC+05:30 Asia/Kolkata', offset: 5.5 },
    { value: 'Asia/Dhaka', label: 'UTC+06:00 Asia/Dhaka', offset: 6 },
    { value: 'Asia/Bangkok', label: 'UTC+07:00 Asia/Bangkok', offset: 7 },
    { value: 'Asia/Shanghai', label: 'UTC+08:00 Asia/Shanghai', offset: 8 },
    { value: 'Asia/Tokyo', label: 'UTC+09:00 Asia/Tokyo', offset: 9 },
    { value: 'Australia/Adelaide', label: 'UTC+09:30 Australia/Adelaide', offset: 9.5 },
    { value: 'Australia/Sydney', label: 'UTC+10:00 Australia/Sydney', offset: 10 },
    { value: 'Pacific/Noumea', label: 'UTC+11:00 Pacific/Noumea', offset: 11 },
    { value: 'Pacific/Auckland', label: 'UTC+12:00 Pacific/Auckland', offset: 12 },
    { value: 'Pacific/Apia', label: 'UTC+13:00 Pacific/Apia', offset: 13 },
    { value: 'Pacific/Kiritimati', label: 'UTC+14:00 Pacific/Kiritimati', offset: 14 },
];

export { timezones };
